apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: answerbot-app
  namespace: poornima-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: answerbot-app
    spec:
      containers:
        - name: slack-answerbot
          image: ministryofjustice/cloud-platform-slack-answerbot:1.1
          # env:
          #   - name: API_KEY
          #     valueFrom:
          #       secretKeyRef:
          #         name: usage-report-api-key
          #         key: token
          ports:
          - containerPort: 4567
