apiVersion: v1
kind: Service
metadata:
  name: answerbot-service
  labels:
    app: answerbot-service
spec:
  ports:
  - port: 4567
    name: https
    targetPort: 4567
  selector:
    app: answerbot-app
