apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: answerbot-app
  namespace: poornima-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: answerbot-app
    spec:
      containers:
        - name: slack-answerbot
          image: poornimak/slash-bot:1.0
          imagePullPolicy: Always
          env:
            - name: SLACK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-api-token
                  key: token
          ports:
          - containerPort: 4567
