apiVersion: apps/v1
kind: Deployment
metadata:
  name: answerbot-app
  namespace: poornima-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: answerbot-app
  template:
    metadata:
      labels:
        app: answerbot-app
    spec:
      containers:
        - name: slack-answerbot
          image: ministryofjustice/cloud-platform-slack-answerbot:1.5
          imagePullPolicy: Always
          env:
            - name: SLACK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-api-token
                  key: token
          ports:
          - containerPort: 4567
